# Generated by Django 5.2.8 on 2026-01-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_customuser_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, unique=True),
        ),
    ]
