# Generated by Django 5.2.8 on 2026-01-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
